steps:
  # Build customer frontend image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/ecommerce-frontend:latest
      - -f
      - frontend/Dockerfile
      - frontend
  
  # Push customer frontend image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/ecommerce-frontend:latest

  # Deploy customer frontend to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ecommerce-frontend
      - --image
      - gcr.io/$PROJECT_ID/ecommerce-frontend:latest
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --min-instances
      - "0"
      - --max-instances
      - "10"
      - --memory
      - 256Mi
      - --cpu
      - "1"
      - --port
      - "3000"
      - --timeout
      - "300"
      - --set-env-vars
      - REACT_APP_API_URL=https://ecommerce-backend-192614808954.us-central1.run.app
    id: deploy-frontend

images:
  - gcr.io/$PROJECT_ID/ecommerce-frontend:latest

# Options for logging configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

