# Northflank deployment configuration
version: 1

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ecommerce
      REDIS_URL: redis://redis:6379
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: ${BACKEND_URL}
    ports:
      - 3000:3000
    depends_on:
      - backend

  # Admin Panel
  admin:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: ${BACKEND_URL}
    ports:
      - 5030:5030
    depends_on:
      - backend

volumes:
  postgres_data:
